#!/bin/bash

# Script to add LSP files to Xcode project
# This script helps you add all the LSP integration files to your Xcode target

echo "=========================================="
echo "LSP Files Addition Helper"
echo "=========================================="
echo ""
echo "The following files need to be added to your Xcode project:"
echo ""
echo "📁 Core/LSP/ (11 files):"
echo "  - LSPTypes.swift"
echo "  - LSPError.swift"
echo "  - LSPLogger.swift"
echo "  - JSONRPCTransport.swift"
echo "  - LanguageServerConfig.swift"
echo "  - DocumentVersionManager.swift"
echo "  - LSPSession.swift"
echo "  - LSPDebouncer.swift"
echo "  - LSPCache.swift"
echo "  - LSPServerPool.swift"
echo "  - LSPManager.swift"
echo ""
echo "📁 Features/Editor/ViewModels/ (1 file):"
echo "  - EditorViewModel.swift"
echo ""
echo "📁 Features/Editor/Views/ (3 files):"
echo "  - CompletionPopupView.swift"
echo "  - DiagnosticsGutterView.swift"
echo "  - HoverPopoverView.swift"
echo ""
echo "=========================================="
echo "MANUAL STEPS (Recommended):"
echo "=========================================="
echo ""
echo "1. Open RatuKidulIDE.xcodeproj in Xcode"
echo ""
echo "2. In the Project Navigator (left sidebar), right-click on 'RatuKidulIDE' folder"
echo ""
echo "3. Select 'Add Files to \"RatuKidulIDE\"...'"
echo ""
echo "4. Navigate to: RatuKidulIDE/Core/LSP/"
echo "   - Select ALL .swift files in this folder"
echo "   - UNCHECK 'Copy items if needed'"
echo "   - CHECK the 'RatuKidulIDE' target"
echo "   - Click 'Add'"
echo ""
echo "5. Repeat step 3-4 for:"
echo "   - RatuKidulIDE/Features/Editor/ViewModels/EditorViewModel.swift"
echo "   - RatuKidulIDE/Features/Editor/Views/CompletionPopupView.swift"
echo "   - RatuKidulIDE/Features/Editor/Views/DiagnosticsGutterView.swift"
echo "   - RatuKidulIDE/Features/Editor/Views/HoverPopoverView.swift"
echo ""
echo "6. Build the project (Cmd+B) to verify all files are added"
echo ""
echo "=========================================="
echo "AFTER ADDING FILES:"
echo "=========================================="
echo ""
echo "Uncomment the LSP integration code in:"
echo "  - RatuKidulIDE/App/AppState.swift"
echo "  - RatuKidulIDE/App/AppDelegate.swift"
echo "  - RatuKidulIDE/Features/Editor/Views/EditorContentView.swift"
echo "  - RatuKidulIDE/Features/Editor/Views/CodeEditorView.swift"
echo ""
echo "Then rebuild and run the app to see LSP features!"
echo ""
